name: SSH Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Check if directory exists on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.144.162.231 '[ -d ~/my-app ] || mkdir ~/my-app'

      - name: Copy code to EC2
        run: rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" -r --exclude='.git/' --exclude='.github/' --exclude='node_modules/' * ubuntu@3.144.162.231:~/my-app/

      - name: Check if Node.js is installed and run deploy.sh
        run: | 
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@3.144.162.231 'command -v node || (cd ~/my-app/redux-tutorial && chmod +x node_install.sh && ./node_install.sh) && cd ~/my-app/redux-tutorial && chmod +x project_deploy.sh && ./project_deploy.sh'
